<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Toro/Toro.fsproj" />
    <ProjectReference Include="../../src/Toro.NN/Toro.NN.fsproj" />
    <ProjectReference Include="../../src/Toro.Hub/Toro.Hub.fsproj" />
    <ProjectReference Include="../../src/Toro.Vision/Toro.Vision.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="TorchSharp-cpu" Version="0.107.0" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="3.119.4" Condition="$([MSBuild]::IsOSPlatform('Linux'))" />
  </ItemGroup>

</Project>
