<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageId>Toro</PackageId>
    <Version>0.1.0</Version>
    <Authors>ryushiaok</Authors>
    <Description>Minimalist ML framework for F# powered by TorchSharp</Description>
    <PackageTags>fsharp;dotnet;ml;torchsharp;tensor</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/toro-ml/toro</RepositoryUrl>
    <RepositoryBranch>main</RepositoryBranch>
    <RepositoryType>git</RepositoryType>
    <NoWarn>FS0760</NoWarn>
    <PackageReleaseNotes>https://github.com/toro-ml/toro/releases</PackageReleaseNotes>
    <PackageProjectUrl>https://github.com/toro-ml/toro</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Error.fs" />
    <Compile Include="Device.fs" />
    <Compile Include="DType.fs" />
    <Compile Include="Shape.fs" />
    <Compile Include="Tensor.fs" />
    <Compile Include="TensorOp.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="TorchSharp" Version="0.107.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

</Project>
