<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Include="TestHelper.fs" />
    <Compile Include="TensorTests.fs" />
    <Compile Include="AutogradTests.fs" />
    <Compile Include="TensorOpTests.fs" />
    <Compile Include="PipeTests.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Toro/Toro.fsproj" />
  </ItemGroup>

</Project>
